version: '3.8'

services:
  # Сервис для Spring Boot приложения
  taskmanagement:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskDB
      SPRING_DATASOURCE_USERNAME: Student
      SPRING_DATASOURCE_PASSWORD: 1769
    depends_on:
      - db

  # Сервис для PostgreSQL базы данных
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: taskDB
      POSTGRES_USER: Student
      POSTGRES_PASSWORD: 1769
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Настройки для постоянного хранения данных базы данных
volumes:
  postgres-data: